# Configuration flags to customize

# The site Name
name: Maxim's blog 

# Short bio or description
description: Maxim's github blog

theme: jekyll-theme-cayman

title: mvmatrosov

# To include the URL of blog post directory control 
permalink: /blog/:year/:month/:day/:title